"""Per-OS instructions for switching DNS resolvers.

netdoctor never changes system settings by itself. ``netdoctor dns --apply`` prints (or
writes to a file with ``--script``) the exact commands for your OS so you can review and
run them yourself — most of them need administrator rights.
"""

from __future__ import annotations

import platform
from dataclasses import dataclass, field

from netdoctor.models import Resolver


@dataclass
class Instruction:
    """A titled block of shell commands."""

    title: str
    commands: list[str]
    note: str = ""
    revert: list[str] = field(default_factory=list)


def current_os() -> str:
    """Return ``linux``, ``macos`` or ``windows``."""
    system = platform.system().lower()
    if system == "darwin":
        return "macos"
    if system.startswith("win"):
        return "windows"
    return "linux"


def dns_instructions(
    resolver: Resolver, os_name: str | None = None, interface: str | None = None
) -> list[Instruction]:
    """Build ready-to-run instructions that point the OS at ``resolver``."""
    target = os_name or current_os()
    addrs = list(resolver.addresses[:2])
    space = " ".join(addrs)
    if target == "macos":
        svc = interface or "Wi-Fi"
        return [
            Instruction(
                f"macOS — network service '{svc}'",
                [
                    f'networksetup -setdnsservers "{svc}" {space}',
                    "sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder",
                ],
                note="List services with: networksetup -listallnetworkservices",
                revert=[f'networksetup -setdnsservers "{svc}" empty'],
            )
        ]
    if target == "windows":
        alias = interface or "Wi-Fi"
        quoted = ",".join(f'"{a}"' for a in addrs)
        return [
            Instruction(
                f"Windows (PowerShell as Administrator) — adapter '{alias}'",
                [
                    f'Set-DnsClientServerAddress -InterfaceAlias "{alias}" '
                    f"-ServerAddresses ({quoted})",
                    "Clear-DnsClientCache",
                ],
                note="List adapters with: Get-NetAdapter",
                revert=[
                    f'Set-DnsClientServerAddress -InterfaceAlias "{alias}" -ResetServerAddresses'
                ],
            )
        ]
    iface = interface or "<interface>"
    return [
        Instruction(
            "Linux — systemd-resolved (temporary, until reboot/reconnect)",
            [f"sudo resolvectl dns {iface} {space}", "sudo resolvectl flush-caches"],
            note="Find the interface with: resolvectl status   (or: ip route get 1.1.1.1)",
            revert=[f"sudo resolvectl revert {iface}"],
        ),
        Instruction(
            "Linux — NetworkManager (persistent)",
            [
                f'nmcli connection modify "<connection>" ipv4.dns "{space}" '
                "ipv4.ignore-auto-dns yes",
                'nmcli connection up "<connection>"',
            ],
            note="List connections with: nmcli connection show --active",
            revert=[
                'nmcli connection modify "<connection>" ipv4.dns "" ipv4.ignore-auto-dns no',
                'nmcli connection up "<connection>"',
            ],
        ),
    ]


def render_script(resolver: Resolver, instructions: list[Instruction], os_name: str) -> str:
    """Render instructions as a commented script (``.sh`` or ``.ps1``) for review."""
    c = "#"
    lines = []
    if os_name != "windows":
        lines.append("#!/bin/sh")
    lines += [
        f"{c} Generated by netdoctor — switch DNS to {resolver.name} "
        f"({', '.join(resolver.addresses)})",
        f"{c} Review before running. netdoctor never runs these commands itself.",
        "",
    ]
    for ins in instructions:
        lines.append(f"{c} --- {ins.title}")
        if ins.note:
            lines.append(f"{c} {ins.note}")
        lines += ins.commands
        if ins.revert:
            lines.append(f"{c} To revert:")
            lines += [f"{c}   {r}" for r in ins.revert]
        lines.append("")
        if os_name == "linux":
            # Only the first Linux variant should run by default; keep others commented.
            break
    if os_name == "linux" and len(instructions) > 1:
        for ins in instructions[1:]:
            lines.append(f"{c} --- Alternative: {ins.title}")
            lines += [f"{c} {cmd}" for cmd in ins.commands]
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"
