"""Shareable reports (`netdoctor report --json/--md`)."""

from __future__ import annotations

import platform
from collections.abc import Sequence
from datetime import datetime, timezone
from typing import Any

from netdoctor import __version__
from netdoctor.dnsbench import explain
from netdoctor.mirrors import best_per_ecosystem
from netdoctor.models import MirrorResult, ResolverScore, ScanSummary, ServiceResult, to_dict


def build_report(
    *,
    scan: Sequence[ServiceResult] | None = None,
    summary: ScanSummary | None = None,
    dns: Sequence[ResolverScore] | None = None,
    mirrors: Sequence[MirrorResult] | None = None,
    resolver: str | None = None,
) -> dict[str, Any]:
    """Assemble a JSON-serialisable report. No IP address of yours is included."""
    report: dict[str, Any] = {
        "tool": "netdoctor-ir",
        "version": __version__,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "platform": {
            "system": platform.system(),
            "release": platform.release(),
            "python": platform.python_version(),
        },
        "resolver": resolver or "system",
    }
    if scan is not None:
        report["scan"] = {"summary": to_dict(summary), "results": to_dict(list(scan))}
    if dns is not None:
        report["dns"] = [
            {**to_dict(s), "rank": i, "note": explain(s)} for i, s in enumerate(dns, 1)
        ]
    if mirrors is not None:
        report["mirrors"] = {
            "results": to_dict(list(mirrors)),
            "best": {k: v.mirror.id for k, v in best_per_ecosystem(mirrors).items()},
        }
    return report


def _ms(v: Any) -> str:
    return "—" if v is None else f"{float(v):.0f} ms"


def _cell(text: Any) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def to_markdown(report: dict[str, Any]) -> str:
    """Render a report dict as GitHub-flavoured Markdown."""
    out = [
        "# netdoctor report",
        "",
        f"- **Generated:** {report['generated_at']} (UTC)",
        f"- **netdoctor:** {report['version']} · **Python:** {report['platform']['python']}"
        f" · **OS:** {report['platform']['system']} {report['platform']['release']}",
        f"- **Resolver used for scan:** {report['resolver']}",
        "",
    ]
    scan = report.get("scan")
    if scan:
        s = scan["summary"]
        out += ["## Developer services", "", f"**{s['headline']}**", ""]
        out += [f"- {tip}" for tip in s["advice"]]
        out += [
            "",
            "| Service | Host | Verdict | HTTP | Total | Why |",
            "|---|---|---|---|---|---|",
        ]
        for r in scan["results"]:
            out.append(
                f"| {_cell(r['service']['name'])} | `{r['service']['host']}` | "
                f"**{r['verdict']}** | {r['status'] or '—'} | {_ms(r['total_ms'])} | "
                f"{_cell(r['reason'])} |"
            )
        out.append("")
    dns = report.get("dns")
    if dns:
        out += [
            "## DNS resolvers",
            "",
            "| # | Resolver | Kind | Address | Answered | Median | Score | Notes |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for d in dns:
            r = d["resolver"]
            out.append(
                f"| {d['rank']} | {_cell(r['name'])} | {r['kind']} | "
                f"`{d['best_address'] or r['addresses'][0]}` | "
                f"{d['answered'] - d['hijacked']}/{d['queries']} | {_ms(d['median_ms'])} | "
                f"{d['score']:.0f} | {_cell(d['note'])} |"
            )
        out.append("")
    mirrors = report.get("mirrors")
    if mirrors:
        out += [
            "## Package mirrors",
            "",
            "| Ecosystem | Mirror | URL | Verdict | Latency | Trust |",
            "|---|---|---|---|---|---|",
        ]
        for m in mirrors["results"]:
            mm = m["mirror"]
            star = " ★" if mirrors["best"].get(mm["ecosystem"]) == mm["id"] else ""
            out.append(
                f"| {mm['ecosystem']} | {_cell(mm['name'])}{star} | `{mm['url']}` | "
                f"**{m['verdict']}** | {_ms(m['ms'])} | {mm['verification']} |"
            )
        out.append("")
    out += [
        "---",
        "",
        "_Generated by [netdoctor-ir](https://github.com/mrzroot/netdoctor-ir) — "
        "a diagnostic tool; it measures, it does not bypass anything._",
        "",
    ]
    return "\n".join(out)
